'use client';
import { useState } from 'react';
import { defaultModel, materialIds, materialNames, modelSettings, visibleCenters, isVisible, type Material, type ModelSettings } from '@/lib/models';
import type { EffectOptions } from '@/lib/creative';
export type EditTool='view'|'material'|'source';
export function Range({label,value,min,max,step=1,unit='',onChange}:{label:string;value:number;min:number;max:number;step?:number;unit?:string;onChange:(v:number)=>void}){
 return <label className="model-range"><span>{label}<output>{value}{unit}</output></span><input type="range" min={min} max={max} step={step} value={value} aria-label={label} onChange={e=>onChange(Number(e.target.value))}/></label>;
}
export function ModelControls({bandId,options,onChange,tool,onTool,brush,onBrush,radius,onRadius,disabled,onPreview}:{bandId:string;options:EffectOptions;onChange:(v:EffectOptions)=>void;tool:EditTool;onTool:(t:EditTool)=>void;brush:Material;onBrush:(v:Material)=>void;radius:number;onRadius:(v:number)=>void;disabled:boolean;onPreview:()=>void}){
 const m=modelSettings(options.model),visible=isVisible(bandId),source=bandId==='radio'||bandId==='gamma';
 const [open,setOpen]=useState(true);
 const change=(patch:Partial<ModelSettings>)=>onChange({...options,model:{...m,...patch}});
 const select=(label:string,key:keyof ModelSettings,items:[string,string][])=> <label className="model-select"><span>{label}</span><select value={String(m[key])} onChange={e=>change({[key]:e.target.value})}>{items.map(([v,name])=><option key={v} value={v}>{name}</option>)}</select></label>;
 const range=(label:string,key:keyof ModelSettings,min:number,max:number,unit='',step=1)=><Range label={label} value={Number(m[key])} min={min} max={max} unit={unit} step={step} onChange={v=>change({[key]:v})}/>;
 return <fieldset className="model-controls" disabled={disabled}><legend>Simulation studio</legend>
 <div className="engine-tabs" role="group" aria-label="Rendering method"><button type="button" aria-pressed={m.engine==='informed'} onClick={()=>change({engine:'informed'})}>Modeled</button><button type="button" aria-pressed={m.engine==='classic'} onClick={()=>{change({engine:'classic',showMaterials:false});onTool('view');}}>Classic</button></div>
 {m.engine==='classic'?<p className="tool-help">The original artistic filters. Switch to Modeled to explore materials, wavelength response, and source assumptions.</p>:<>
 {select('Display palette','palette',[['native','Band colors'],['gray','Grayscale'],['iron','Warm thermal'],['viridis','Viridis-style'],['ice','Ice']])}
 <p className="tool-help">Palette changes the display colors, not the assumed signal.</p>
 <button className="model-disclosure" type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>Adjust this simulation <span>{open?'−':'+'}</span></button>
 {open&&<div className="model-settings">
 {visible&&<>{range('Wavelength shift','wavelengthShift',-25,25,' nm')}<p className="tool-help">Filter center: {Math.max(400,Math.min(700,visibleCenters[bandId]+m.wavelengthShift))} nm. Smooth RGB spectral estimate.</p>{range('Filter bandwidth','bandwidth',5,120,' nm')}</>}
 {!visible&&!source&&<>{select('Scene assumptions','scene',[['outdoor','Landscape / botanical'],['urban','City / buildings'],['portrait','People / exposed skin'],['wildlife','Animals / fur'],['indoor','Indoor / objects']])}{select('Unmarked material','material',[['auto','Use color hints (guesses)'],...materialIds.map(id=>[id,materialNames[id]] as [string,string])])}</>}
 {bandId==='nir'&&range('NIR wavelength','nirWavelength',720,1000,' nm',10)}
 {bandId==='thermal'&&<>{select('Environment','lighting',[['sun','Sunlit'],['shade','Shaded'],['night','Night']])}{range('Assumed ambient','ambient',-10,45,' °C')}{range('Assumed skin temperature','subjectTemperature',0,80,' °C')}<p className="tool-help">Skin uses this temperature; fur is modeled 5 °C cooler. Other materials use environment offsets. Surface emissivity and reflected ambient radiation are included. No temperature is measured.</p></>}
 {bandId==='uv'&&<>{select('UV imaging method','uvMode',[['reflected','Reflected near-UV'],['fluorescence','UV-induced visible fluorescence']])}<p className="tool-help">Fluorescence colors are illustrative material assumptions; they do not reveal hidden markings or identify chemicals.</p></>}
 {bandId==='xray'&&<>{range('Assumed thickness','thickness',0,100,' mm')}<label className="model-select"><span>Photon energy</span><select aria-label="Photon energy" value={m.energy} onChange={e=>change({energy:Number(e.target.value) as 60|80|100})}><option value={60}>60 keV</option><option value={80}>80 keV</option><option value={100}>100 keV</option></select></label>{range('Texture in thickness','texture',0,100,'%')}{select('X-ray display','polarity',[['dense-white','Dense material is white'],['transmission','Transmitted signal is white']])}<p className="tool-help">NIST attenuation data for water, polyethylene, and iron. Other materials use simplified proxies. Texture adds assumed surface relief; it is not depth or anatomy. Set texture to 0 for a uniform slab.</p></>}
 {bandId==='microwave'&&<>{range('Surface roughness','roughness',0,100,'%')}{range('Assumed moisture','moisture',0,100,'%')}{range('Incidence angle','angle',10,80,'°')}{range('Radar speckle','speckle',0,100,'%')}<p className="tool-help">A simplified backscatter illustration. Buildings and hidden geometry are not reconstructed.</p></>}
 {source&&<><p className="tool-help">One hypothetical source on the photo plane. No source is detected. Use opacity or Split view to see its position against the photograph.</p>{range('Source X','sourceX',0,100,'%')}{range('Source Y','sourceY',0,100,'%')}{range('Source power','sourcePower',0,100,'%')}{range(bandId==='radio'?'Signal reach':'Detector blur','spread',3,60,'%')}<button className={'tool-button '+(tool==='source'?'active':'')} aria-pressed={tool==='source'} onClick={()=>onTool(tool==='source'?'view':'source')}>{tool==='source'?'Done placing source':'Place source on image'}</button>{bandId==='gamma'&&<>{range('Exposure','exposure',1,100)}{range('Counting noise','noise',0,100,'%')}</>}</>}
 </div>}
 {!visible&&!source&&<details className="material-editor"><summary>Correct the material guesses</summary><p className="tool-help">Choose a material and tap the image to stamp a circular region. Coordinates follow zoom and pan. These are your assumptions, not identified materials.</p><label className="model-select"><span>Stamp material</span><select value={brush} onChange={e=>onBrush(e.target.value as Material)}>{materialIds.map(id=><option key={id} value={id}>{materialNames[id]}</option>)}</select></label><Range label="Stamp radius" value={radius} min={2} max={40} unit="%" onChange={onRadius}/><div className="model-actions"><button className={'tool-button '+(tool==='material'?'active':'')} aria-pressed={tool==='material'} onClick={()=>onTool(tool==='material'?'view':'material')}>{tool==='material'?'Done editing':'Stamp on image'}</button><button className="tool-button" disabled={m.regions.length>=48} onClick={()=>change({regions:[...m.regions,{x:.5,y:.5,radius:radius/100,material:brush}]})}>Stamp at center</button><button className="tool-button" disabled={!m.regions.length} onClick={()=>change({regions:m.regions.slice(0,-1)})}>Undo</button><button className="tool-button" disabled={!m.regions.length} onClick={()=>change({regions:[]})}>Clear</button></div><label className="model-check"><input type="checkbox" checked={m.showMaterials} onChange={e=>change({showMaterials:e.target.checked})}/>Show material map</label><p className="tool-help">{m.regions.length} / 48 regions. At 48, undo or clear to add more. Marks clear when you change photographs; favorites retain them.</p><div className="material-key">{materialIds.map((id,i)=><span key={id}><i style={{background:['#89909a','#abd56c','#3998c6','#e5ac8f','#be9edf','#a68458','#d7e0e6','#74c9be','#566887'][i]}}/>{materialNames[id]}</span>)}</div></details>}
 {!visible&&!source&&<p className="tool-help">Color hints blend softly with a general surface. The material map shows the strongest guess; stamps use the material you choose.</p>}
 <div className="model-actions"><button className="text-tool" onClick={()=>{change({...defaultModel,scene:m.scene,regions:[]});onTool('view');}}>Reset simulation settings</button><button className="text-tool mobile-preview" onClick={onPreview}>View image ↑</button></div>
 </>}
 </fieldset>;
}
