import fs from 'node:fs/promises';
import path from 'node:path';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
const root=path.resolve(import.meta.dirname,'..');
process.chdir(root);
await fs.mkdir('.build',{recursive:true});
await fs.mkdir('outputs',{recursive:true});
const css=await fs.readFile('app/globals.css','utf8');
const result=await postcss([tailwind({base:root,optimize:true})]).process(css,{from:path.join(root,'app/globals.css'),to:path.join(root,'.build/styles.css')});
await fs.writeFile('.build/styles.css',result.css);
await fs.copyFile('assets/geist.woff2','.build/geist.woff2');
await import('./export-public.mjs');
await import('./export-offline.mjs');
const appLicense=await fs.readFile('LICENSE','utf8');
const thirdParty=[await fs.readFile('THIRD_PARTY_NOTICES.md','utf8'),await fs.readFile('licenses/Geist-OFL.txt','utf8'),await fs.readFile('licenses/DEPENDENCIES.txt','utf8')].join('\n\n');
await fs.writeFile('outputs/public_html/LICENSE.txt',appLicense);
await fs.writeFile('outputs/public_html/THIRD-PARTY-LICENSES.txt',thirdParty);
const index=await fs.readFile('outputs/public_html/index.html','utf8');
await fs.writeFile('outputs/public_html/index.html',index.replace('</head>','<link rel="license" href="./LICENSE.txt"></head>'));
const offline=await fs.readFile('outputs/Spectrum.html','utf8');
const escape=text=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
await fs.writeFile('outputs/Spectrum.html',offline.replace('</head>','<template id="license-notices">'+escape(appLicense+'\n\n'+thirdParty)+'</template></head>'));
